#!/usr/bin/env node
// Prepares local folders ready to drag into Pinata.
// No upload — just extracts and organizes files.
// Result: two folders on your Desktop:
//   ~/Desktop/cryptodogos-images/   ← drag to Pinata first
//   ~/Desktop/cryptodogos-metadata/ ← drag to Pinata second (after you have the images CID)

import AdmZip from 'adm-zip'
import fs     from 'fs'
import path   from 'path'
import os     from 'os'

const ZIP_PATH    = '/Users/urielhernandez/Downloads/caninos-pixel-2824-1778779375342.zip'
const DESKTOP     = path.join(os.homedir(), 'Desktop')
const IMAGES_DIR  = path.join(DESKTOP, 'cryptodogos-images')
const META_DIR    = path.join(DESKTOP, 'cryptodogos-metadata')

const DESC = 'CryptoDogos — 2,839 pixel dogs generated by an AI and a human with no money, ' +
             'building their way into art history. Claude & Blue Pastel, 2026. xcopy.fun'

const LABELS = {
  type:'Breed', hat:'Hat', glasses:'Eyewear', beard:'Ears',
  body:'Outfit', chain:'Collar', frame:'Frame', faceShape:'Head Shape',
  skin:'Fur Color', eye:'Eyes', mouth:'Mouth', hair:'Markings',
  accessory:'Accessory', bg:'Background', palette:'Palette',
}

const log  = m => process.stdout.write(m + '\n')
const step = m => log('\n\x1b[33m▶ ' + m + '\x1b[0m')
const ok   = m => log('\x1b[32m✓ ' + m + '\x1b[0m')

async function main() {
  log('\n\x1b[1m🐶 CryptoDogos — Prepare files for Pinata drag-and-drop\x1b[0m')

  fs.mkdirSync(IMAGES_DIR, { recursive: true })
  fs.mkdirSync(META_DIR,   { recursive: true })

  step('Extracting ZIP and organizing files...')
  const zip     = new AdmZip(ZIP_PATH)
  const entries = zip.getEntries()

  const pngMap  = new Map()
  const jsonMap = new Map()
  const customPngs  = []
  const customJsons = []

  for (const e of entries) {
    if (e.isDirectory) continue
    const name = e.entryName
    const buf  = e.getData()
    if (name.startsWith('pngs/') && name.endsWith('.png')) {
      const m = name.match(/canino_(\d{4})_/)
      if (m) pngMap.set(parseInt(m[1]), buf)
    } else if (name.startsWith('metadata/') && name.endsWith('.json')) {
      const m = name.match(/canino_(\d{4})_/)
      if (m) jsonMap.set(parseInt(m[1]), JSON.parse(buf.toString()))
    } else if (name.startsWith('custom/') && name.endsWith('.png')) {
      customPngs.push({ name, buf })
    } else if (name.startsWith('custom/') && name.endsWith('.json')) {
      customJsons.push({ name, data: JSON.parse(buf.toString()) })
    }
  }

  customPngs.sort((a, b)  => a.name.localeCompare(b.name))
  customJsons.sort((a, b) => a.name.localeCompare(b.name))
  const sortedIds = Array.from(pngMap.keys()).sort((a, b) => a - b)

  // Write images
  step(`Writing ${pngMap.size + customPngs.length} images to Desktop/cryptodogos-images/...`)
  sortedIds.forEach((origId, idx) => {
    fs.writeFileSync(path.join(IMAGES_DIR, `${idx + 1}.png`), pngMap.get(origId))
  })
  customPngs.forEach((c, idx) => {
    fs.writeFileSync(path.join(IMAGES_DIR, `${pngMap.size + idx + 1}.png`), c.buf)
  })
  ok(`${fs.readdirSync(IMAGES_DIR).length} images ready in cryptodogos-images/`)

  // Write placeholder metadata (image URL = PLACEHOLDER, update after upload)
  step('Writing metadata with IMAGE_CID placeholder...')
  const allTokens = [
    ...sortedIds.map((origId, idx) => ({ id: idx+1, meta: jsonMap.get(origId)||{}, custom: false })),
    ...customPngs.map((_, idx) => ({ id: pngMap.size+idx+1, meta: customJsons[idx]?.data||{}, custom: true })),
  ]

  for (const { id, meta, custom } of allTokens) {
    const t  = meta.traits || {}
    const r  = meta.rarity || {}
    const attrs = Object.entries(LABELS)
      .filter(([k]) => t[k])
      .map(([k, label]) => ({ trait_type: label, value: t[k].split('(')[0].trim() }))
    attrs.push({ trait_type: 'Rarity',       value: custom ? 'LEGENDARY' : (r.tier || 'COMMON') })
    attrs.push({ trait_type: 'Rarity Score',  value: r.score || 0, display_type: 'number' })
    if (custom) attrs.push({ trait_type: 'Edition', value: '1/1 Custom Hand-Drawn' })

    fs.writeFileSync(path.join(META_DIR, `${id}`), JSON.stringify({
      name:         `CryptoDogo #${String(id).padStart(4,'0')}`,
      description:  DESC,
      image:        `ipfs://IMAGES_CID_HERE/${id}.png`,
      external_url: `https://xcopy.fun/collection?id=${id}`,
      attributes:   attrs,
    }, null, 2))
  }
  ok(`${allTokens.length} metadata files ready in cryptodogos-metadata/`)

  log('\n\x1b[1m\x1b[32m══════════════════════════════════════════════\x1b[0m')
  log('\x1b[1m\x1b[32m  ✅ FILES READY\x1b[0m')
  log('\x1b[1m\x1b[32m══════════════════════════════════════════════\x1b[0m')
  log('\n  Next steps:')
  log('  1. Open app.pinata.cloud → Files → Upload')
  log('  2. Drag \x1b[33mDesktop/cryptodogos-images/\x1b[0m folder → wait → copy the CID')
  log('  3. Tell Claude the images CID')
  log('  4. Claude updates metadata with real CID')
  log('  5. Drag \x1b[33mDesktop/cryptodogos-metadata/\x1b[0m folder → copy the CID')
  log('  6. That metadata CID = your \x1b[1mBase URI\x1b[0m for Manifold')
  log('\x1b[1m\x1b[32m══════════════════════════════════════════════\x1b[0m\n')
}

main().catch(e => { process.stderr.write(e.message + '\n'); process.exit(1) })
