#!/usr/bin/env node
// CryptoDogos — IPFS upload (Pinata V3, batched directories)
// Images split into 4 batches (~710 each, ~8MB/batch) → 4 directory pins
// Metadata uploaded as one directory → base URI
// Total pins used: 5 out of 500 free limit
//
// Usage: npm run upload-ipfs

import AdmZip   from 'adm-zip'
import axios    from 'axios'
import FormData from 'form-data'
import fs       from 'fs'
import path     from 'path'
import { fileURLToPath } from 'url'

const __dirname  = path.dirname(fileURLToPath(import.meta.url))
const ROOT       = path.join(__dirname, '..')
const ZIP_PATH   = '/Users/urielhernandez/Downloads/caninos-pixel-2824-1778779375342.zip'
const OUT_DIR    = path.join(ROOT, 'scripts', 'ipfs-prep')
const PINATA_JWT = process.env.PINATA_JWT
const BATCH_SIZE = 710  // images per directory upload (~8MB each)

const DESC = 'CryptoDogos — 2,839 pixel dogs generated by an AI and a human with no money, ' +
             'building their way into art history. Claude & Blue Pastel, 2026. xcopy.fun'

const LABELS = {
  type:'Breed', hat:'Hat', glasses:'Eyewear', beard:'Ears',
  body:'Outfit', chain:'Collar', frame:'Frame', faceShape:'Head Shape',
  skin:'Fur Color', eye:'Eyes', mouth:'Mouth', hair:'Markings',
  accessory:'Accessory', bg:'Background', palette:'Palette',
}

const log  = m => process.stdout.write(m + '\n')
const step = m => log('\n\x1b[33m▶ ' + m + '\x1b[0m')
const ok   = m => log('\x1b[32m✓ ' + m + '\x1b[0m')
const err  = m => { log('\x1b[31m✗ ' + m + '\x1b[0m'); process.exit(1) }

// Upload a buffer map as one directory to Pinata V3
async function uploadBatch(bufMap, pinName) {
  log(`  Uploading ${bufMap.size} files as "${pinName}"...`)
  const form = new FormData()
  for (const [filename, {buf, mime}] of bufMap) {
    form.append('file', buf, { filename, contentType: mime, knownLength: buf.length })
  }
  form.append('name', pinName)

  const res = await axios.post('https://uploads.pinata.cloud/v3/files', form, {
    maxBodyLength: Infinity,
    maxContentLength: Infinity,
    headers: { ...form.getHeaders(), Authorization: `Bearer ${PINATA_JWT}` },
    onUploadProgress: e => {
      if (e.loaded) process.stdout.write(`\r    ${(e.loaded/1024/1024).toFixed(1)} MB uploaded...   `)
    },
  })
  process.stdout.write('\n')
  const cid = res.data?.data?.cid
  if (!cid) throw new Error(`No CID returned: ${JSON.stringify(res.data)}`)
  ok(`  CID: ${cid}`)
  return cid
}

async function main() {
  log('\n\x1b[1m🐶 CryptoDogos — IPFS Upload (batched directories)\x1b[0m')
  if (!PINATA_JWT) err('PINATA_JWT not set in .env')

  fs.mkdirSync(path.join(OUT_DIR, 'metadata'), { recursive: true })

  // ── Extract ZIP ──────────────────────────────────────────
  step('Extracting ZIP...')
  const zip     = new AdmZip(ZIP_PATH)
  const entries = zip.getEntries()
  const pngMap  = new Map()
  const jsonMap = new Map()
  const customPngs  = []
  const customJsons = []

  for (const e of entries) {
    if (e.isDirectory) continue
    const name = e.entryName; const buf = e.getData()
    if (name.startsWith('pngs/') && name.endsWith('.png')) {
      const m = name.match(/canino_(\d{4})_/); if (m) pngMap.set(parseInt(m[1]), buf)
    } else if (name.startsWith('metadata/') && name.endsWith('.json')) {
      const m = name.match(/canino_(\d{4})_/); if (m) jsonMap.set(parseInt(m[1]), JSON.parse(buf.toString()))
    } else if (name.startsWith('custom/') && name.endsWith('.png'))  { customPngs.push({ name, buf }) }
    else if (name.startsWith('custom/') && name.endsWith('.json')) { customJsons.push({ name, data: JSON.parse(buf.toString()) }) }
  }

  customPngs.sort((a,b) => a.name.localeCompare(b.name))
  customJsons.sort((a,b) => a.name.localeCompare(b.name))
  const sortedIds = Array.from(pngMap.keys()).sort((a,b) => a-b)

  const allTokens = [
    ...sortedIds.map((origId, idx) => ({ id:idx+1, buf:pngMap.get(origId), meta:jsonMap.get(origId)||{}, custom:false })),
    ...customPngs.map((c,idx) => ({ id:pngMap.size+idx+1, buf:c.buf, meta:customJsons[idx]?.data||{}, custom:true })),
  ]
  ok(`${allTokens.length} tokens ready`)

  // ── Upload images in batches ─────────────────────────────
  step(`Uploading images in batches of ${BATCH_SIZE}...`)
  const imageCIDMap = new Map() // tokenId → `ipfs://CID/filename.png`
  const cidsFile    = path.join(OUT_DIR, 'batch-cids.json')

  // Load previous progress
  let savedCIDs = {}
  if (fs.existsSync(cidsFile)) {
    savedCIDs = JSON.parse(fs.readFileSync(cidsFile, 'utf8'))
    log(`  Resuming: ${Object.keys(savedCIDs).length} batches already done`)
  }

  const totalBatches = Math.ceil(allTokens.length / BATCH_SIZE)

  for (let b = 0; b < totalBatches; b++) {
    const start  = b * BATCH_SIZE
    const end    = Math.min(start + BATCH_SIZE, allTokens.length)
    const batchKey = `batch_${b}`

    if (savedCIDs[batchKey]) {
      log(`  Batch ${b+1}/${totalBatches}: already uploaded (CID: ${savedCIDs[batchKey]})`)
      // Reconstruct image CID map from saved data
      for (let i = start; i < end; i++) {
        imageCIDMap.set(allTokens[i].id, `ipfs://${savedCIDs[batchKey]}/${allTokens[i].id}.png`)
      }
      continue
    }

    const bufMap = new Map()
    for (let i = start; i < end; i++) {
      const t = allTokens[i]
      bufMap.set(`${t.id}.png`, { buf: t.buf, mime: 'image/png' })
    }

    log(`  Batch ${b+1}/${totalBatches}: tokens ${start+1}–${end}`)
    const cid = await uploadBatch(bufMap, `cryptodogos-images-batch${b+1}`)
    savedCIDs[batchKey] = cid
    fs.writeFileSync(cidsFile, JSON.stringify(savedCIDs, null, 2))

    for (let i = start; i < end; i++) {
      imageCIDMap.set(allTokens[i].id, `ipfs://${cid}/${allTokens[i].id}.png`)
    }
  }

  ok(`All images uploaded (${totalBatches} batches)`)

  // ── Build metadata ────────────────────────────────────────
  step('Building OpenSea metadata...')
  const metaDir = path.join(OUT_DIR, 'metadata')

  for (const { id, meta, custom } of allTokens) {
    const t = meta.traits || {}; const r = meta.rarity || {}
    const attrs = Object.entries(LABELS)
      .filter(([k]) => t[k])
      .map(([k,label]) => ({ trait_type:label, value:t[k].split('(')[0].trim() }))
    attrs.push({ trait_type:'Rarity',       value: custom ? 'LEGENDARY' : (r.tier||'COMMON') })
    attrs.push({ trait_type:'Rarity Score', value: r.score||0, display_type:'number' })
    if (custom) attrs.push({ trait_type:'Edition', value:'1/1 Custom Hand-Drawn' })

    fs.writeFileSync(path.join(metaDir, `${id}`), JSON.stringify({
      name:         `CryptoDogo #${String(id).padStart(4,'0')}`,
      description:  DESC,
      image:        imageCIDMap.get(id) || `ipfs://MISSING/${id}.png`,
      external_url: `https://xcopy.fun/collection?id=${id}`,
      attributes:   attrs,
    }, null, 2))
  }
  ok(`${allTokens.length} metadata files ready`)

  // ── Upload metadata as one directory ─────────────────────
  step('Uploading metadata directory...')
  const files = fs.readdirSync(metaDir)
  const metaBufMap = new Map()
  for (const f of files) {
    const buf = fs.readFileSync(path.join(metaDir, f))
    metaBufMap.set(f, { buf, mime:'application/json' })
  }

  const metaCID = await uploadBatch(metaBufMap, 'cryptodogos-metadata')
  fs.writeFileSync(path.join(OUT_DIR, 'base-uri.txt'), `ipfs://${metaCID}/`)

  // ── Done ──────────────────────────────────────────────────
  log('\n\x1b[1m\x1b[32m══════════════════════════════════\x1b[0m')
  log('\x1b[1m\x1b[32m  ✅ UPLOAD COMPLETE\x1b[0m')
  log('\x1b[1m\x1b[32m══════════════════════════════════\x1b[0m')
  log(`\n  Tokens uploaded: ${allTokens.length}`)
  log(`  Image batches:   ${totalBatches} (${totalBatches} pins used)`)
  log(`  Metadata:        ipfs://${metaCID}/`)
  log(`\n  \x1b[1mBASE URI for Manifold:\x1b[0m`)
  log(`  \x1b[33mipfs://${metaCID}/\x1b[0m`)
  log('\n  Paste in: Manifold → Contract → Token URI')
  log('\x1b[1m\x1b[32m══════════════════════════════════\x1b[0m\n')
}

main().catch(e => err(e.message))
